
import Flynn

class HelloWorld: Actor {
    public var x = 5
    
    private func _bePrint() {
        print("hi")
    }
    
}
// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension HelloWorld {

    @discardableResult
    public func bePrint() -> Self {
        unsafeSend(_bePrint)
        return self
    }

}
